Pin Out Reference Image/Colors
nomis/logitech-z906 pull request #3
Opened 2022-07-16 19:56 UTC by Nozemi

- Pin out reference image, with colors to map the original console cable's wires.
- Added a color column to the pin out table.
- Moved the images into their own directory.
- Updated the image reference in the firmware.rst file so it references the new image location.

2022-07-16 20:02 UTC, nomis commented
Could you use SVG instead of JPEG for `images/console-port-diagram.jpg`?

2022-07-16 20:14 UTC, nomis commented
The pins in the diagram are from the perspective of the amplifier connector but the colours are for the console cable which has the pins in the mirrored order...

2022-07-16 20:38 UTC, nomis requested changes

2022-07-16 20:38 UTC, nomis commented on interface.rst
> +*Image reference of the port, showing which wire color is what on the original console cable.*
You need to indent this with 3 spaces so that it's a caption and not a separate paragraph.

2022-07-16 20:38 UTC, nomis commented on interface.rst
> +*Image reference of the port, showing which wire color is what on the original console cable.*
(I don't think it needs italics)

2022-07-16 20:38 UTC, nomis commented on interface.rst
> +**NOTE! This is from the sub/amp side, not the numbers on the cable!** *(yes the connector on the cable is labeled with numbers)*
I'd just state that the connector is labelled with numbers that are different from those of the connector. It should be implied that these are the DB-15 pin numbers...

2022-07-22 20:05 UTC, nomis commented
The colours in here don't match those on https://www.reddit.com/r/hardwarehacking/comments/hnpprk/hacking_the_logitech_z906_speaker_system/.

There's no reason why Logitech would have to use the same colour wires on every batch so it's possible they're not always the same. There are two variants of the console - with and without an exposed programming port - so these could have different wire colours too.

2022-07-23 18:02 UTC, Nozemi commented
> 

I noticed that the wiring colors aren't matching, not sure what's up with that. Haven't really had time to look into it either, so I haven't done anything more with this pull request.

I have both of the consoles at hand, so I suppose I could check to see if there is a difference between them.

However, the wiring diagram on the Reddit link seems to work, at least for the cable I cut off the connectors of.

Closing this PR, will open a new one if I can find time to produce something definitively correct, and useful.

2022-07-23 18:02 UTC, closed without merging

2022-07-23 19:34 UTC, nomis commented
> However, the wiring diagram on the Reddit link seems to work, at least for the cable I cut off the connectors of.

I don't recommend cutting the cables because they use a standard connector... I suggest you get a [VGA extension cable](https://en.wikipedia.org/wiki/VGA_connector) next time and cut that in half. The colours of the wires are only useful if you're cutting cables otherwise the pin numbering is sufficient.